

export const Constants = {
    app: '#dataworld',
    title: 'DataWorld',
    version: 'V1.0.0',
    countries : [
        { value: 1 , name: 'Mexico', namea2: 'mx' },
        { value: 2 , name: 'USA', namea2: 'us' },
        { value: 3 , name: 'France', namea2: 'fr' },
        { value: 4 , name: 'Germany', namea2: 'de' },
        { value: 5 , name: 'Italy', namea2: 'it' },
        { value: 6 , name: 'UK', namea2: 'gb' },
        { value: 7 , name: 'Belgium', namea2: 'be' },
        { value: 8 , name: 'Netherlands', namea2: 'nl' },
        { value: 9 , name: 'Sweden', namea2: 'se' },
        { value: 10 , name: 'Switzerland', namea2: 'ch' },
        { value: 11 , name: 'Austria', namea2: 'at' },
        { value: 12 , name: 'Finland', namea2: 'fi' },
        { value: 13 , name: 'Portugal', namea2: 'pt' },
        { value: 14 , name: 'Turkey', namea2: 'tr' },
        { value: 15 , name: 'Russia', namea2: 'ru' },
        { value: 16 , name: 'Denmark', namea2: 'dk' },
        { value: 17 , name: 'Canada', namea2: 'ca' },
        { value: 18 , name: 'India', namea2: 'in' },
        { value: 19 , name: 'Greece', namea2: 'gr' },
        { value: 20 , name: 'Spain', namea2: 'es' },
        { value: 21 , name: 'Egypt', namea2: 'eg' },
        { value: 22 , name: 'Argentina', namea2: 'ar' },
        { value: 23 , name: 'Hungary', namea2: 'hu' },
        { value: 24 , name: 'Poland', namea2: 'pl' },
        { value: 25 , name: 'North Korea', namea2: 'kp' },
        { value: 26 , name: 'China', namea2: 'cn' },
        { value: 27 , name: 'Brazil', namea2: 'br' },
        { value: 28 , name: 'Czech Republic', namea2: 'cz' },
        { value: 29 , name: 'Norway', namea2: 'no' },
        { value: 30 , name: 'South Africa', namea2: 'za' },
        { value: 31 , name: 'Australia', namea2: 'au' },
        { value: 32 , name: 'Ukraine', namea2: 'ua' },
        { value: 33 , name: 'Indonesia', namea2: 'id' },
        { value: 34 , name: 'Japan', namea2: 'jp' },
        { value: 35 , name: 'Morocco', namea2: 'ma' },
        { value: 36 , name: 'Bulgaria', namea2: 'bg' },
        { value: 37 , name: 'Chile', namea2: 'cl' },
        { value: 39 , name: 'Croatia', namea2: 'hr' },
        { value: 40 , name: 'Serbia', namea2: 'rs' },
        { value: 41 , name: 'Nigeria', namea2: 'ng' },
        { value: 42 , name: 'Pakistan', namea2: 'pk' },
        { value: 43 , name: 'Slovakia', namea2: 'sk' },
        { value: 44 , name: 'Peru', namea2: 'pe' },
        { value: 45 , name: 'Tunisia', namea2: 'tn' },
        { value: 46 , name: 'Senegal', namea2: 'sn' },
        { value: 47 , name: 'Slovenia', namea2: 'si' },
        { value: 48 , name: 'Philippines', namea2: 'ph' },
        { value: 49 , name: 'Ghana', namea2: 'gh' },
        { value: 50 , name: 'Romania', namea2: 'ro' }

    //     'México', 'Estados Unidos', 'Francia', 'Alemania', 'Italia', 'Reino Unido', 'Bélgica', 'Paises Bajos', 'Suecia', 'Suiza', 'Austria', 'Finlandia', 'Portugal', 
    //     'Turquía', 'Rusia', 'Dinamarca', 'Cánada', 'India', 'Grecia', 'España', 'Egipto', 'Argentina', 'Hungría', 'Polonia', 'Rumania', 'República de Corea del Norte', 
    //     'China', 'Brasil', 'República Checa', 'Noruega', 'Sudáfrica', 'Australia', 'Ucrania', 'Indonesia', 'Japon', 'Marruecos', 'Bulgaria', 'Chile', 'Croacia',
    //      'Serbia', 'Nigeria', 'Malasia', 'Pakistán', 'Eslovaquia', 'Perú', 'Túnez', 'Senegal', 'Eslovenia', 'Filipinas', 'Ghana'


    //     'Mexico', 'USA', 'France', 'Germany','Italy','UK','Belgium','Netherlands','Sweden','Switzerland','Austria','Finland','Portugal','Turkey','Russia','Denmark','Canada',
    //     'India','Greece','Spain','Egypt','Argentina','Hungary','Polonia','Poland',
    //   //'North Korea','China','Brazil',
    // 'Czech Republic','Norway','South Africa','Australia','Ukraine','Indonesia','Japan','Morocco','Bulgaria','Chile','Croatia','Serbia','Nigeria','Malasia',
    // 'Pakistan','Slovakia','Peru','Tunisia','Senegal','Slovenia','Philippines','Ghana'
    ]
}